name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install nightly
      run: rustup install nightly-2021-03-01
    - name: Setup env
      run: rustup target add wasm32-unknown-unknown --toolchain nightly-2021-03-01-x86_64-unknown-linux-gnu
    - name: Build
      run: cargo +nightly-2021-03-01 build --verbose
    - name: Test
      run: cargo +nightly-2021-03-01 test
