name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: centos7

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo +nightly-2021-03-01 build --verbose
    - name: Run tests
      run: cargo +nightly-2021-03-01 test --verbose
